### ISSUE TITLE
Browse hander: SQLite object library on FreeBSD machines

### ISSUE THREAD

**Issue by todolson** [uchicago-library/vufind#43]
The browse indexes on FreeBSD do not work because the JVM cannot find the right SQLite native driver:
```
Caused by: java.lang.Exception: Error loading native library: /org/sqlite/native/FreeBSD/amd64/libsqlitejdbc.so
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:241)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:63)
        at org.sqlite.NativeDB.load(NativeDB.java:50)
        at org.sqlite.Conn.open(Conn.java:161)
```

Need to give the right parameters to the JVM.

- [ ] examine old `vufind.sh` script for the additional FreeBDS parameters
- [ ] add to `solr.sh` (may need to look deeply)

**Comment by seanfilipov** [comment]
To make browse table working on FreeBSD machines(local hosts), we need to remove sqlite-jdbc-3.7.15-SNAPSHOT.jar file from solr/vufind/jar/ directory.
